# Site settings
title: "Ruby Wynn"
email: ruby@rubywynn.com
description: "Ruby Wynn's Personal Site"
baseurl: ""
url: "http://rubywynn.com"
title_description: "I am a Biology major at St Mary's University."
title_image: ""
google_analytics: 
disqus_account: 
github_repository: https://github.com/r-wynn/r-wynn.github.io/
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  r-wynn
linkedin_link: www.linkedin.com/in/r-wynn
google_plus_link: 
stackoverflow_link:

# Footer
footer_left: ""
footer_right: ""

# Build settings

permalink: pretty
exclude: [vendor]
